#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@

    cat /etc/pagekite.d/* > /tmp/pagekite.rc
    rm /etc/pagekite.d/*
    mv /tmp/pagekite.rc /etc/pagekite.d/pagekite.rc
}

# installs pagekite
install pagekite

# tell the world what we've done!
echo 'TurnKey patched with PageKite' >> /etc/issue
