#!/bin/bash -ex

install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@

    # Configure PageKite to 
    while read line
    do
        ( echo "$line" | grep -q -i https  && echo "https server" ) ||
        ( echo "$line" | grep -q -i http && echo "http server" ) ||
        ( echo "$line" | grep -q -i ssh 
    done < /etc/confconsole/services.txt
}

install pagekite

echo 'TurnKey patched with PageKite' >> /etc/issue

